#!/bin/sh
# Script By Alkahanet


systemctl stop nginx
rm -r /var/log/nginx
mkdir -p /var/log/nginx
touch /var/log/nginx/access.log
touch /var/log/nginx/error.log
sleep 3
systemctl start nginx
sleep 5
systemctl restart nginx
